### ISSUE TITLE
Getting Bitnami Neo4J running on openshift

### ISSUE THREAD

**Issue by wautersp** [bitnami/bitnami-docker-neo4j#3]
I wonder if anyone succeeded running the Bitnami Neo4J container on openshift?

I'm on Openshift 3.9, on premise installation.

I have deployed the image.
I mounted 2 volumes:
/data
/bitnami

I created a route.
I do get a login page, but I can't connect to bolt://neo4j-domain:8756

I get:
ServiceUnavailable: WebSocket connection failure. Due to security constraints in your web browser, the reason for the failure is not available to this Neo4j Driver. Please use your browsers development console to determine the root cause of the failure. Common reasons include the database being unavailable

In browser console, I see:
Firefox can’t establish a connection to the server at ws://neo4j-domain:8756/.

(I also tried the default Bolt port 7687)
(I replaced full URL by neo4j-domain in this topic)

I'm not sure what values I should override in the neo4j.conf file?

**Comment by miguelaeh** [comment]
Hi @wautersp ,
I have test it again, and it works for me. Have you exposed the 3 ports that neo4j use? I mean, by default you need to expose the ports 7474, 7473 and 7687. I have done that configuring a LoadBalancer, paste here my LoadBalancer:
```
kind: Service
apiVersion: v1
metadata:
  name: my-lb
spec:
  selector:
    app: neo4j
  ports:
  - protocol: TCP
    port: 80
    name: http
    targetPort: 7474
  - protocol: TCP
    name: ws
    port: 7473
    targetPort: 7473
  - protocol: TCP
    name: ws-2
    port: 7687
    targetPort: 7687
  type: LoadBalancer
```

I think if you configure a Route for the 8756 port pointing to a ClusterIp service inside your cluster (I guess you change the default port, right?) the other two ports are not exposed, so you get that error because they are not accessible.
Did you configure to expose the 3 ports needed?
